default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: example_angular_app_development
test:
  <<: *default
  database: example_angular_app_test
production:
  <<: *default
  database: example_angular_app_production
